### ISSUE TITLE
Fix the warnings that XSPEC is giving when reading .pha files

### ISSUE THREAD

**Issue by lucabaldini** [lucabaldini/ximpol#25] opened 2016-01-16 00:13 UTC
More specifically:

```
***Warning: POISSERR keyword is missing or of wrong format, assuming FALSE.
***Warning!  One or more spectra are missing responses,
           and are not suitable for fit.
***Warning: No TLMIN keyword value for response matrix FCHAN column.
        Will assume TLMIN = 1.
```

This should be relatively straightforward.

**Comment by ndilalla** [comment] 2016-07-07 09:43
Reading the online documentation ([https://heasarc.gsfc.nasa.gov/docs/heasarc/ofwg/docs/spectra/ogip_92_007/node6.html](url)), seems that the warnings are caused by missing keywords in the pha file header. More specifically:
-  POISSERR: it is not required if a STAT_ERR column is present (as in our case) but it is recommended for clarity. If STAT_ERR is to be used for the errors then POISSERR is set to false.
- TLMIN: it gives the minimum legal value for the values in the column named 'CHANNEL' (ie. the lowest PHA channel possible for the instrument under the current operational mode, irrespective of whether or not that channel is stored as part of the PHA dataset).

For what concerns the responses, XSPEC searches for RESPFILE and ANCRFILE keywords in the header in order to automatically load the response files. We currently have only the IRFNAME keyword and we manually load the response files using it.

In my opinion we should implement the required keywords in the pha header. What do you think about it?

**Comment by ndilalla** [comment] 2016-07-12 13:10
An update on this issue:
- The POISSERR keyword was set but in the wrong way ('T' instead of True). Moreover we want to set it to False in order to use the statistical errors.
- TLMIN keyword was set yet. Actually the XSPEC warning refers to the same missing keyword in the rmf file header (issue #21). I added also TLMAX just for clarity.
- RESPFILE and ANCRFILE keywords were both set to None, so that XSPEC was unable to automatically load the response files, giving rise to the warning. So I added the rmf and arf paths to the pha header.

```
@@ -219,10 +220,9 @@ class xBinTableHDUPHA1(xBinTableHDUBase):
         ('CHANTYPE', 'PI'),
         ('HDUVERS' , '1.2.1', 'OGIP version number'),
         ('TLMIN1'  , 0      , 'first channel number'),
+        ('TLMAX1'  , 255    , 'last channel number'),
         ('CORRSCAL', 1.     , 'scaling for correction file'),
-        ('POISSERR', 'T'    , 'is error Poisson?'),
-        ('RESPFILE', None),
-        ('ANCRFILE', None),
+        ('POISSERR', False  , 'use statistical errors'),
         ('BACKFILE', None),
         ('CORRFILE', None),
         ('SYS_ERR' , 0.),
@@ -261,7 +261,10 @@ class xEventBinningPHA1(xEventBinningBase):
         ]
         spec_hdu = xBinTableHDUPHA1(data)
         spec_hdu.setup_header(self.event_file.primary_keywords())
-        keywords = [('EXPOSURE', total_time, 'exposure time')]
+        irf_name = evt_header['IRFNAME']
+        keywords = [('EXPOSURE', total_time, 'exposure time'),
+                    ('RESPFILE', irf_file_path(irf_name, 'rmf')),
+                    ('ANCRFILE', irf_file_path(irf_name, 'arf'))]
         spec_hdu.setup_header(keywords)
         hdu_list = fits.HDUList([primary_hdu, spec_hdu])
         hdu_list.info()
```

**Comment by ndilalla** [comment] 2016-07-14 11:25
This is done. Closing it.

**Closed as completed by ndilalla** 2016-07-14 11:25 UTC
